### ISSUE TITLE
Can't view OS

### ISSUE THREAD

**Issue by generica** [VPAC/patchman#2]
Running 299d7b04938faa92d61cf55d17e54bb931562ac2

Going to an OS page, such as https://help.vlsci.unimelb.edu.au/patchman/os/5 just redirects to https://help.vlsci.unimelb.edu.au/patchman/

Same as if I go to the OS Groups page, and click from there.

**Comment by furlongm** [comment]
Fixed in dd9121bd4c279c1fe7b2e7c478b6dda8d5f7c068
