### ISSUE TITLE
new client issue on centos

### ISSUE THREAD

**Issue by generica** [VPAC/patchman#4]
[root@bruce-m sbin]# patchman-client 
sed: -e expression #1, char 72: unknown option to `s'
sed: -e expression #1, char 56: unknown option to`s'

[root@bruce ~]# patchman-client 
sed: -e expression #1, char 72: unknown option to `s'                                                                                                                                                          
sed: -e expression #1, char 56: unknown option to`s'  
sed: -e expression #1, char 72: unknown option to `s'                                                                                                                                                          
sed: -e expression #1, char 56: unknown option to`s'

**Comment by furlongm** [comment]
Can you run with bash -x and see what line is causing this?

**Comment by generica** [comment]
++ yum repolist enabled --verbose
++ sed -e 's/\/'\''/'\''/g'
++ sed -e 's/'\''more)'\''//'
++ awk '{ if ($1=="Repo-name") {printf "'\''"; for (i=3; i<NF; i++) printf
$i " "; printf $NF" x86_64'\'' "} if ($1=="Repo-baseurl" ||
$1=="Repo-baseurl:" || $1=="Repo-mirrors") { url=1; comma=match($NF,",");
if (comma) out=substr($NF,1,comma-1); else out=$NF; printf "'\''"out"'\''
"; } else { if (url==1) { if ($1==":") { comma=match($NF,","); if (comma)
out=substr($NF,1,comma-1); else out=$NF; printf "'\''"out"'\'' "; } else
{url=0; print "";} } } }'
++ sed -e 's/ '\'' /'\'' /'
- for i in '$(yum repolist enabled --verbose 2>/dev/null | awk '\''{ if
  ($1=="Repo-name") {printf "'\''"'\''"'\''"; for (i=3; i<NF; i++) printf $i
  " "; printf $NF"'\''" ${host_arch}'\''"'\'' "} if ($1=="Repo-baseurl" ||
  $1=="Repo-baseurl:" || $1=="Repo-mirrors") { url=1; comma=match($NF,",");
  if (comma) out=substr($NF,1,comma-1); else out=$NF; printf
  "'\''"'\''"'\''"out"'\''"'\''"'\'' "; } else { if (url==1) { if ($1==":") {
  comma=match($NF,","); if (comma) out=substr($NF,1,comma-1); else out=$NF;
  printf "'\''"'\''"'\''"out"'\''"'\''"'\'' "; } else {url=0; print "";} } }
  }'\'' | sed -e "s/\/'\''/'\''/g" | sed -e "s/'\''more)'\''//" | sed -e "s/
  '\'' /'\'' /")'
  ++ cut -d ''\''' -f 2
  ++ echo ''\''xCAT configured yum repository for centos5.7/x86_64/x86_64
  x86_64'\'' '\''http://10.0.100.1/install/centos5.7/x86_64/updates/x86_64'\''
  '
- name='xCAT configured yum repository for centos5.7/x86_64/x86_64 x86_64'
  ++ echo ''
  ++ grep ''\''xCAT configured yum repository for centos5.7/x86_64/x86_64
  x86_64'\'''
  ++ sed -e 's/priority=(.*) '\''xCAT configured yum repository for
  centos5.7/x86_64/x86_64 x86_64'\''/\1/'
  sed: -e expression #1, char 72: unknown option to `s'
- priority=
- '[' '' == '' ']'
- priority=99
  ++ echo ''\''xCAT configured yum repository for centos5.7/x86_64/x86_64
  x86_64'\'' '\''http://10.0.100.1/install/centos5.7/x86_64/updates/x86_64'\''
  '
  ++ sed -e 's/'\''xCAT configured yum repository for centos5.7/x86_64/x86_64
  x86_64'\''/'\''xCAT configured yum repository for centos5.7/x86_64/x86_64
  x86_64'\'' '\''99'\''/'
  sed: -e expression #1, char 56: unknown option to `s'
- j=
- echo ''\''rpm'\'''

Repo-id      : local-centos5-updates-x86_64-x86_64
Repo-name    : xCAT configured yum repository for centos5.7/x86_64/x86_64
Repo-updated : Thu Jan 12 06:26:31 2012
Repo-pkgs    : 537
Repo-size    : 1.2 G
Repo-baseurl : http://10.0.100.1/install/centos5.7/x86_64/updates/x86_64/
Repo-expire  : 3,600 second(s) (last: Wed Mar 28 10:20:53 2012)
Repo-exclude : kernel*
Repo-excluded: 32

Repo-id      : local-centos5.7-x86_64-x86_64
Repo-name    : xCAT configured yum repository for centos5.7/x86_64/x86_64
Repo-updated : Thu Jan 12 06:26:31 2012
Repo-pkgs    : 569
Repo-size    : 1.5 G
Repo-baseurl : http://10.0.100.1/install/centos5.7/x86_64//updates/x86_64/
Repo-expire  : 3,600 second(s) (last: Wed Mar 28 10:20:53 2012)

Repo-id      : updates
Repo-name    : CentOS-5 - Updates
Repo-updated : Thu Apr  7 07:14:30 2011
Repo-pkgs    : 244
Repo-size    : 669 M
Repo-baseurl : http://10.0.100.1/CentOS/5.6/updates/x86_64/
Repo-expire  : 3,600 second(s) (last: Fri Mar 23 04:05:56 2012)

repolist: 1,350

**Comment by furlongm** [comment]
Fxied in 00415b0
