### ISSUE TITLE
Patchman doesn't like an xcat repo

### ISSUE THREAD

**Issue by generica** [VPAC/patchman#5]
xCAT 2 Core packages x86_64
http://xcat.sourceforge.net/yum/2.3/xcat-core/repodata/repomd.xml.bz2 - HTTP Error 404: Not Found
http://xcat.sourceforge.net/yum/2.3/xcat-core/repodata/repomd.xml.gz - HTTP Error 404: Not Found
http://xcat.sourceforge.net/yum/2.3/xcat-core/repodata/repomd.xml - yum rpm repo found.
Downloading repo info (1/2):       100%|########################################################################################################################################################|Time: 00:00:00
Downloading repo info (2/2):       100%|########################################################################################################################################################|Time: 00:00:00
Repo checksum has not changed, not updating packages
https://sourceforge.net/projects/xcat/files/yum/2.7/xcat-core/repodata/repomd.xml.bz2 - yum rpm repo found.
Downloading repo info (1/2):       100%|########################################################################################################################################################|Time: 00:00:00
Error obtaining primary url from https://sourceforge.net/projects/xcat/files/yum/2.7/xcat-core/repodata/repomd.xml.bz2, disabling refresh.

**Comment by furlongm** [comment]
This is due to sourceforge giving a 302 redirect back to a html web page:

> wget https://sourceforge.net/projects/xcat/files/yum/2.7/xcat-core/repodata/repomd.xml.bz2
> asking libproxy about url 'https://sourceforge.net/projects/xcat/files/yum/2.7/xcat-core/repodata/repomd.xml.bz2'
> libproxy suggest to use 'direct://'
> --2012-04-12 12:05:27--  https://sourceforge.net/projects/xcat/files/yum/2.7/xcat-core/repodata/repomd.xml.bz2
> Resolving sourceforge.net (sourceforge.net)... 216.34.181.60
> Connecting to sourceforge.net (sourceforge.net)|216.34.181.60|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: http://sourceforge.net/projects/xcat/files/yum/2.7/xcat-core/repodata/repomd.xml.bz2 [following]
> asking libproxy about url 'http://sourceforge.net/projects/xcat/files/yum/2.7/xcat-core/repodata/repomd.xml.bz2'
> libproxy suggest to use 'direct://'
> --2012-04-12 12:05:28--  http://sourceforge.net/projects/xcat/files/yum/2.7/xcat-core/repodata/repomd.xml.bz2
> Connecting to sourceforge.net (sourceforge.net)|216.34.181.60|:80... connected.
> HTTP request sent, awaiting response... 302 Moved Temporarily
> Location: http://sourceforge.net/projects/xcat/files/ [following]
> asking libproxy about url 'http://sourceforge.net/projects/xcat/files/'
> libproxy suggest to use 'direct://'
> --2012-04-12 12:05:28--  http://sourceforge.net/projects/xcat/files/
> Reusing existing connection to sourceforge.net:80.
> HTTP request sent, awaiting response... 200 OK
> Length: 27723 (27K) [text/html]
> Saving to: `repomd.xml.bz2'

100%[===================================================================================================================================================================================================>] 27,723      55.5K/s   in 0.5s

If the xcat 2.7 repo also gets mirrored under http://xcat.sourceforge.net/yum along with the previous releases, this would fix this issue.

**Comment by furlongm** [comment]
Can you try the current git and see if it fixes the issue?

**Comment by generica** [comment]
yup

**Comment by furlongm** [comment]
Actually, this may not have been totally fixed, fba391a does a better job and seems to work for me.
