### ISSUE TITLE
jquery include incorrect

### ISSUE THREAD

**Issue by generica** [VPAC/patchman#6]
[Wed Apr 18 09:15:09 2012] [error] [client 128.250.103.229] File does not exist: /var/lib/patchman/media/js/jquery-ui.min.js, referer: https://help.vlsci.unimelb.edu.au/patchman/

File doesn't exist, but is mentioned in the base template

**Comment by furlongm** [comment]
It seems to be there, maybe you need a git pull?

**Comment by generica** [comment]
Must have been bad timing between pulls

On Apr 19, 2012 1:20 PM, "Marcus Furlong" <
reply@reply.github.com>
wrote:
