### ISSUE TITLE
Yum repos on a debian host

### ISSUE THREAD

**Issue by generica** [VPAC/patchman#7]
Patchman seems to assume that if yum is installed, then repos can be found.
This happens on a debian host:

root@vss:~# patchman-client -v
Patchman configuration seems ok:
Patchman Server: https://help.vlsci.unimelb.edu.au/patchman
Tags: Server
Report: 0
Finding installed rpms...
Finding installed debs...
Finding yum repos...
sed: can't read /etc/yum.repos.d/*.repo: No such file or directory
Finding apt repos...
Sending data to https://help.vlsci.unimelb.edu.au/patchman with curl...
Command is : /usr/bin/curl --insecure -F verbose="1" -F host="vss.pcf.vlsci.unimelb.edu.au" -F tags="Server" -F kernel="2.6.32-12-pve" -F arch="x86_64" -F protocol="1" -F os="Debian 6.0.5" -F report="0" -F packages=</tmp/tmp.1eVAIQr2P2 -F repos=</tmp/tmp.yYDMZxwcRj -F reboot="ServerCheck" https://help.vlsci.unimelb.edu.au/patchman/reports/upload/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25258    0     0  100 25258      0   273k --:--:-- --:--:-- --:--:--  280k
Deleting /tmp/tmp.1eVAIQr2P2...
Deleting /tmp/tmp.yYDMZxwcRj...

Which on silent sends a cron error because of the failed sed

Would be good if it worked with an empty /etc/yum/repos.d directory.

**Comment by furlongm** [comment]
fixed in 5753dcd

**Comment by furlongm** [comment]
properly fixed in d5953f2
